Repository jitsi/jitsi-meet, pull requests merged in 2020-07, with the labels that each got.

#7207 prosody muc_size plugin, room get info error fix
  resources/prosody-plugins/mod_muc_size.lua
Labels: info:cla-signed

#6951 add feature flag to enable / disable conference timer
  react/features/base/flags/constants.js
  react/features/conference/components/native/NavigationBar.js
Labels: info:cla-signed

#6608 Update main-eo.json
  lang/main-eo.json
Labels: localization

#5148 feat(chat): Make chat push content to the side in large view
  css/_chat.scss
  css/_toolbars.scss
  css/_videolayout_default.scss
  modules/UI/videolayout/LargeVideoManager.js
  react/features/chat/actions.js
  react/features/chat/components/web/Chat.js
  react/features/chat/constants.js
  react/features/conference/components/web/Conference.js
  react/features/conference/components/web/index.js
  react/features/large-video/components/LargeVideo.web.js
  react/features/toolbox/components/web/Toolbox.js
  react/features/toolbox/functions.web.js
Labels: feature-request, info:feedback-needed, ui/ux

#5124 feat(chat): Make chat push content to the side in tile view
  css/_base.scss
  css/filmstrip/_tile_view.scss
  react/features/filmstrip/actions.web.js
  react/features/filmstrip/components/native/TileView.js
  react/features/filmstrip/components/web/Filmstrip.js
  react/features/filmstrip/middleware.web.js
  react/features/filmstrip/subscriber.web.js
Labels: info:feedback-needed

#6070 Improve accessibility of Buttons in Webapp
  react/features/base/toolbox/components/AbstractButton.js
  react/features/base/toolbox/components/ToolboxItem.web.js
  react/features/toolbox/components/web/ToolbarButton.js
Labels: accessibility, ui/ux, web

#6555 fix(native-ui): specify the correct keyboard type and content on iOS so autocomplete and keyboards work correctly
  react/features/settings/components/native/SettingsView.js
Labels: ios, mobile, ui/ux

#6986 Error message printed for incompatible distros
  resources/install-letsencrypt-cert.sh
Labels: packaging

#6451 Pass JWT token to close page
  react/features/app/actions.js
Labels: wontfix

#7380 Adding responsive to jitsi logo, buttons and hiding some part of the interface
  css/_responsive.scss
  css/_variables.scss
  css/main.scss
  modules/UI/UI.js
  react/features/toolbox/components/web/Toolbox.js
Labels: ui/ux, web
