Repository jitsi/jitsi-meet, pull requests merged in 2020-06, with the labels that each got.

#6935 rn,responsive-ui: refactor dimensions detection
  react/features/app/components/App.native.js
  react/features/base/responsive-ui/components/AspectRatioAware.js
  react/features/base/responsive-ui/components/DimensionsDetector.native.js
  react/features/base/responsive-ui/components/index.js
  react/features/base/responsive-ui/components/styles.js
  react/features/base/responsive-ui/middleware.native.js
  react/features/base/responsive-ui/reducer.js
  react/features/conference/components/native/Conference.js
  react/features/conference/components/native/Labels.js
  react/features/conference/components/web/Labels.js
  react/features/filmstrip/components/native/Filmstrip.js
  react/features/filmstrip/components/native/TileView.js
  react/features/large-video/components/LargeVideo.native.js
Labels: ui/ux

#5361 external_api: add start/stop recording commands
  modules/API/API.js
  modules/API/external/external_api.js
Labels: api

#6921 add missing and fix wrong turkish translation
  lang/main-tr.json
Labels: localization

#6725 main-fr.json : remove duplicated key introduced by #6461
  lang/main-fr.json
Labels: localization

#6615 Marathi language
  lang/languages-mr.json
  lang/languages.json
  lang/main-mr.json
  webpack.config.js
Labels: info:feedback-needed, localization

#6857 rn: adds youtube player for mobile app
  conference.js
  package-lock.json
  package.json
  react/features/base/participants/components/ParticipantView.native.js
  react/features/base/participants/functions.js
  react/features/display-name/components/native/DisplayNameLabel.js
  react/features/filmstrip/components/native/Thumbnail.js
  react/features/toolbox/components/native/OverflowMenu.js
  react/features/youtube-player/actionTypes.js
  react/features/youtube-player/actions.js
  react/features/youtube-player/components/AbstractEnterVideoLinkPrompt.js
  react/features/youtube-player/components/VideoShareButton.js
  react/features/youtube-player/components/_.native.js
  react/features/youtube-player/components/index.js
  react/features/youtube-player/components/native/EnterVideoLinkPrompt.js
  react/features/youtube-player/components/native/YoutubeLargeVideo.js
  react/features/youtube-player/components/native/index.js
  react/features/youtube-player/components/native/styles.js
  react/features/youtube-player/index.js
  react/features/youtube-player/middleware.js
  react/features/youtube-player/reducer.js
Labels: mobile

#7018 fix(UI): add playsinline attr for video element
  modules/UI/videolayout/LocalVideo.js
  react/features/base/media/components/web/Video.js
  react/features/device-selection/components/VideoInputPreview.js
  react/features/settings/components/web/video/VideoSettingsContent.js
Labels: browser-support

#7116 Updated greek translation
  lang/main-el.json
Labels: localization

#5964 Added ssl options for SubjectAlternativeName (SAN) Closes #5547
  debian/jitsi-meet-web-config.postinst
Labels: packaging

#6841 Adding serverURL configuration for MDM/EMM through Managed Configurat…
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/org/jitsi/meet/MainActivity.java
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/xml/app_restrictions.xml
  react/features/app/components/App.native.js
  react/features/base/flags/constants.js
  react/features/settings/components/native/SettingsView.js
  react/features/settings/functions.js
Labels: android, info:feedback-needed

#6788 Adding isSharingScreen() to external API
  modules/API/API.js
  modules/API/external/external_api.js
Labels: api
