Repository jitsi/jitsi-meet, pull requests merged in 2020-05, with the labels that each got.

#6588 lang: add Basque to the list of available languages
  lang/languages.json
Labels: localization

#6657 fix: Fixed browser language detect (close #5987)
  react/features/base/i18n/customNavigatorDetector.js
  react/features/base/i18n/languageDetector.web.js
Labels: info:cla-signed

#6670 moves adding of the jitsiViewListener from initialize to onCreate
  android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivity.java
Labels: android

#6692 ios: try to leave the meeting when the app is terminating
  ios/app/src/AppDelegate.m
  ios/app/src/ViewController.h
  ios/app/src/ViewController.m
Labels: ios

#6436 Add a flag "toolbox.alwaysVisible" to react native
  react/features/base/flags/constants.js
  react/features/toolbox/functions.native.js
Labels: info:cla-signed

#6674 update react-emoji-render to v1.2.4
  package-lock.json
  package.json
Labels: info:cla-signed

#6701 build: fix using parallell make
  Makefile
Labels: packaging

#6731 doc: replace documentation with the handbook
  CONTRIBUTING.md
  doc/README.md
  doc/api.md
  doc/cloud-api.md
  doc/coding-style.md
  doc/development.md
  doc/faq.md
  doc/integrations.md
  doc/manual-install.md
  doc/mobile-dropbox.md
  doc/mobile-google-auth.md
  doc/mobile.md
  doc/quick-install.md
  doc/scalable-installation.md
  doc/sipgw-config.md
  doc/speakerstats-prosody.md
  doc/turn.md
  resources/cloud-api.swagger
Labels: documentation

#6707 ios: fix PiP window sshowing conference controls
  ios/sdk/src/picture-in-picture/PiPViewCoordinator.swift
Labels: ios

#6750 doc: move mobile docs to the handbook
  android/README.md
  ios/README.md
Labels: documentation

#6741 Fix links on README.md
  README.md
Labels: documentation

#6716 webpack-server-dev: don't proxy /lang/
  webpack.config.js
Labels: info:cla-signed

#6700 Fixed using deeplinks using external API
  react/features/deep-linking/components/DeepLinkingMobilePage.web.js
Labels: info:cla-signed

#6792 doc: update README.md
  README.md
Labels: documentation

#6710 Fix passwordLabel translation
  lang/main-de.json
Labels: localization

#6796 Update main-de.json
  lang/main-de.json
Labels: localization

#6800 deps: replace jsrsasign
  package-lock.json
  package.json
  react/features/calendar-sync/web/microsoftCalendar.js
Labels: dependencies

#6795 Retry "external_api: fixed using deeplinks"
  react/features/deep-linking/components/DeepLinkingMobilePage.web.js
Labels: mobile, web

#6141 Update of main fr translation
  lang/main-fr.json
Labels: localization

#6717 improve "open in app" page
  lang/main-de.json
  lang/main-enGB.json
  lang/main-ja.json
  lang/main-nl.json
  lang/main.json
  react/features/deep-linking/components/DeepLinkingMobilePage.web.js
Labels: info:cla-signed, info:feedback-needed

#6818 debian/control: add missing build dependency on nodejs
  debian/control
Labels: info:cla-signed, packaging

#6787 feat(browser-support): show option to join via browser on supported mobile browsers
  react/features/base/environment/environment.js
  react/features/deep-linking/components/DeepLinkingMobilePage.web.js
  react/features/deep-linking/functions.js
Labels: mobile

#5680 Allow translation of accessibility label string "Edit your profile"
  react/features/toolbox/components/web/OverflowMenuProfileItem.js
Labels: localization

#5909 "toggleCamera" = "Переключить камеру"
  lang/main-ru.json
Labels: info:feedback-needed, localization

#6577 Update main.json
  lang/main.json
Labels: localization

#6690 Added Greek language translation
  lang/languages-el.json
  lang/main-el.json
Labels: localization

#6732 [i18n] Update for Occitan
  lang/languages-oc.json
  lang/main-oc.json
Labels: localization

#6587 Include slovenian translations
  lang/languages-enGB.json
  lang/languages-sl.json
  lang/languages.json
  lang/main-sl.json
  react/features/base/i18n/BuiltinLanguages.native.js
Labels: localization

#6760 Improvements to Swedish
  lang/main-sv.json
Labels: localization

#6840 Update main-uk.json
  lang/main-uk.json
Labels: localization

#6848 Retry "lang: adding arabic translation #6679"
  lang/languages-ar.json
  lang/languages.json
  lang/main-ar.json
  react/features/base/i18n/BuiltinLanguages.native.js
Labels: localization

#6850 Update spanish translation
  lang/main-es.json
  lang/main-esUS.json
Labels: localization

#6856 update main-de.json
  lang/main-de.json
Labels: localization

#6851 Update 1-bug-report.md
  .github/ISSUE_TEMPLATE/1-bug-report.md
Labels: documentation

#6551 Update lang readme to match reality
  lang/readme.md
Labels: localization

#6862 Add translations for RO lang
  lang/languages-ro.json
  lang/languages.json
  lang/main-ro.json
Labels: info:feedback-needed, localization

#6815 fix(SecurityDialog): fix button overflow
  css/modals/invite/_info.scss
  css/modals/invite/_invite_more.scss
  css/modals/security/_security.scss
  react/features/conference/components/web/InviteMore.js
Labels: web

#6773 deps: run npm audit fix
  package-lock.json
  package.json
Labels: dependencies

#6879 config: don't enable H.264 by default on P2P
  config.js
Labels: config

#6882 Update main-de.json to add some missing fields
  lang/main-de.json
Labels: localization

#6890 rn: fixup room lock prompt messsage
  react/features/room-lock/components/RoomLockPrompt.native.js
Labels: mobile

#6897 labels: dont disable all labels when VIDEO_QUALITY_LABEL_DISABLED is set
  react/features/conference/components/web/Conference.js
  react/features/conference/components/web/Labels.js
Labels: ui/ux

#6900 chore(deps): Update lib-jitsi-meet, callstats using full URL.
  package-lock.json
  package.json
Labels: dependencies

#5728 feat(subtitles): Disable for guests.
  react/features/subtitles/components/AbstractClosedCaptionButton.js
  react/features/subtitles/components/ClosedCaptionButton.native.js
Labels: info:feedback-needed, ui/ux

#6908 fix(config): Add missing capScreenshareBitrate to config.js
  config.js
Labels: config
