Repository jitsi/jitsi-meet, pull requests merged in 2020-11, with the labels that each got.

#8013 Automatically assign feature-request tag to issues
  .github/ISSUE_TEMPLATE/2-feature-request.md
Labels: hacktoberfest-accepted

#8031 allow wildcard in token issuer verification
  resources/prosody-plugins/token/util.lib.lua
Labels: info:cla-signed

#7751 Update russian translation
  lang/main-ru.json
Labels: localization
